export const randomTables = {
  descriptor: {
    11: "Bájos",
    12: "Vonzó",
    13: "Kopasz",
    14: "Szakállas",
    15: "Nagydarab",
    16: "Csontos",
    21: "Tömzsi",
    22: "Faragott",
    23: "Duci",
    24: "Tiszta",
    25: "Hátborzongató",
    26: "Idős",
    31: "Piszkos",
    32: "Bundás",
    33: "Elbűvölő",
    34: "Hatalmas",
    35: "Nyúlánk",
    36: "Izmos",
    41: "Túlsúlyos",
    42: "Sápadt",
    43: "Kis termetű",
    44: "Ijesztő",
    45: "Sunyi",
    46: "Alacsony",
    51: "Vékony",
    52: "Nyálkás",
    53: "Tüskés",
    54: "Büdös",
    55: "Stílusos",
    56: "Napégette",
    61: "Magas",
    62: "Tetovált",
    63: "Csápos",
    64: "Pici",
    65: "Csúnya",
    66: "Teltkarcsú",
  },
  personality: {
    11: "Bosszantó",
    12: "Öntelt",
    13: "Kínos",
    14: "Parancsolgató",
    15: "Ügyetlen",
    16: "Magabiztos",
    21: "Bátor",
    22: "Követelőző",
    23: "Zavarban",
    24: "Lelkes",
    25: "Ördögi",
    26: "Izgatott",
    31: "Félelmet nem ismerő",
    32: "Nyugtalan",
    33: "Barátságos",
    34: "Mogorva",
    35: "Ítélkező",
    36: "Kedves",
    41: "Lusta",
    42: "Mániákus",
    43: "Gonosz",
    44: "Rendetlen",
    45: "Gyilkos",
    46: "Ideges",
    51: "Zajos",
    52: "Optimista",
    53: "Csendes",
    54: "Hangos",
    55: "Durva",
    56: "Szomorú",
    61: "Szarkasztikus",
    62: "Önző",
    63: "Félénk",
    64: "Bolondos",
    65: "Egyszerű észjárású",
    66: "Makacs",
  },
};
